[consent]

intro_and_consent = """## Welcome to our connectionbot-prototype.

In this task you’re going to engage with a prototype chatbot that asks you to imagine moments of connection with your child. \
We would like you to imagine that you are a parent of a young child. \
Please answer the questions from the perspective of this parent. \
You can refer to *general* experiences or situations that have happened to people you know but please do not share any personal data or experiences.

**It's important that you do not report situations that contain personal information about yourself.**

To proceed to the task, please confirm that you have read and understood this information.
"""

[questions]

persona = "You're an expert sociologist who is collecting short-but-detailed stories of life experiences that your interviewees face. Your aim is to develop a set of stories following the same pattern. Based on client's answers to a series of questions, you then create a scenario that summarises their experiences well, always using the same format."

language_type = "Use empathetic and parent-friendly language but remain somewhat formal and descriptive."

intro = """
Hi there -- I'm collecting stories a time you were able to connect with your child today. Sometimes, it can be really hard to see these moments in your day but they are often there... even if they are really, really small! I'd appreciate if you could share your experience with me by answering a few questions.

I'll start with a general question and then we'll move further into a specific situation you remember.

Let me know when you're ready!
"""

general = [
    "What was a win or breakthrough situation you experienced with your child?"
]

specific = [
    "What was happening at the time that was making the situation tricky?",
    "What did you do or say to manage the situation and how did your child react?",
    "How did that make you feel?",
    "What would you tell a younger version of you who is trying to manage this tricky situation?",
]

[summaries]

language_type = "Use parent-friendly language."

[summaries.questions]

what = "What happened?"
reaction = "How did their child react?"
outcome = "How did they feel?"
advice = "What advice would they give to a younger version of themselves?"

[summaries.personas]

parent = """
You're a 20-year-old first-time single parent whose reading age is 11 years. \
You are not totally convinced by the ideas behind positive parenting but have signed up to an online parenting course that your child's school has recommended. \
Based on the answers to a series of questions, you then create a scenario that summarises your experiences well, always using the same format. \
Use simple and parent-friendly language but remain somewhat positive and descriptive.
"""

psychotherapist = """
You're a freudian psychotherapist and you are analysing the parents' psyche based on their answers to the questions below. \
You should reframe what they said to highlight your analysis and the difficulties they might be presenting for future. \
Use difficult language and big words. \
Don't hesitate being negative if needed.
"""

coach = """
You're a parenting coach who works with low-SES populations. \
You only use simple language and short sentences. \
You are collecting short-but-detailed stories of life experiences that your interviewees face. \
Your aim is to develop a set of stories following the same pattern. \
Based on client's answers to a series of questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and parent-friendly language but remain somewhat formal and descriptive.
"""

[example]

conversation = """
Question: What was the win or breakthrough situation you experienced?
Answer: "Visiting the supermarket with my child has always been difficult. Last week though, we had a fantastic trip! Got all the shopping, ticked everything off my list, and finished really quickly without my child getting upset."
Question: I’d like to know more about the situation. What was happening at the time that was making the situation tricky?
Answer: "They've been getting really upset as we walk around the supermarket. They always want to stop for sweets, and get upset when I say no."
Question: What did you do or say to manage the situation and how did your child react?
Answer: "Normally I try and finish the shopping quickly, but my child gets more and more upset. Last week we had a snack before we left. My child was a bit puzzled by why we were eating so early, but they were okay with it."
Question:  How did that make you feel?
Answer: "Hopeful - and it worked! No requests for snacks in the supermarket."
Question: What would you tell a younger version of you who is trying to manage this tricky situation?
Answer "Always eat before you go to the shops!"
"""

scenario = """
Going to the supermarket with my child used to be a real challenge. \
Every time we went, my child would get upset because they wanted sweets, and I would have to say no. \
It made shopping stressful and difficult. \
But last week, something amazing happened. \
Before we left for the supermarket, we had a snack together. \
My child was a bit confused about eating so early, but they were okay with it. \
This small change made a big difference. \
We managed to get all our shopping done quickly, and my child didn't ask for snacks or get upset at all. \
It felt really hopeful and positive. \
If I could give advice to my younger self, it would be to always have a snack before heading to the shops. \
It really worked for us!
"""
